print(bold().."\n\n")
print(white()     ..[[      /\      ]])
print(cyanBright()..[[     /  \     ]])
print(cyan()      ..[[    /\   \    ]])
print(blueBright()..[[   /      \   ]])
print(blue()      ..[[  /   ,,   \  ]])
print(              [[ /   |  |  -\ ]])
print(              [[/_-''    ''-_\]])
print(reset())
